import { describe, expect, it, vi } from 'vitest';
import { Agent } from '../src/vendor/ruflo/agent';
import { Task } from '../src/vendor/ruflo/task';
import { safeJsonParse } from '../src/vendor/ruflo/json-security';
import { makeTasks, executeRun, selectAgent } from '../src/lib/orchestrator';
import { retrieve, PromptCache } from '../src/lib/memory';
import { complete, listModels, ProviderError, validateEndpoint } from '../src/lib/provider';
import { exportRun } from '../src/lib/storage';
import type { StartMessage, Run } from '../src/lib/types';
const message = (): StartMessage => ({ type: 'start', runId: crypto.randomUUID(), goal: 'Design browser knowledge search', workflow: 'build', connection: { mode: 'remote', endpoint: 'https://api.example.com/v1', model: 'test-model', token: 'never-export-this-token', maxTokens: 512 }, knowledge: [{ id: 'note', title: 'Browser knowledge', content: 'Use keyword search for the first version.', createdAt: new Date().toISOString() }] });

describe('Ruflo browser adaptation', () => {
  it('keeps lifecycle transitions and dependencies', () => { const t = Task.create({ title: 'test', description: '', type: 'review', dependencies: ['previous'] }); expect(t.areDependenciesSatisfied(new Set())).toBe(false); expect(t.areDependenciesSatisfied(new Set(['previous']))).toBe(true); expect(() => t.start()).toThrow(); t.queue(); t.assign('agent'); t.start(); t.complete('done'); expect(t.status).toBe('completed'); expect(t.output).toBe('done'); });
  it('matches agents by capability', () => { const agents = ['planning', 'review'].map(type => Agent.create({ name: type, role: 'custom', domain: 'browser', capabilities: [type] })); const t = Task.create({ title: 'review', description: '', type: 'review' }); expect(selectAgent(agents, t)?.name).toBe('review'); });
  it('builds a five-stage dependency graph', () => { for (const workflow of ['build', 'research', 'review'] as const) { const tasks = makeTasks(workflow); expect(tasks).toHaveLength(5); expect(tasks[1].dependencies).toEqual([tasks[0].id]); expect(tasks[3].dependencies).toEqual([tasks[1].id, tasks[2].id]); } });
  it('strips dangerous object keys', () => { const value = safeJsonParse<{ safe: number }>(' {"safe":1,"__proto__":{"polluted":true},"constructor":{},"nested":{"prototype":1}} '); expect(value.safe).toBe(1); expect(Object.hasOwn(value, '__proto__')).toBe(false); expect(Object.hasOwn(value, 'constructor')).toBe(false); });
});

describe('memory', () => {
  it('retrieves matching notes but not irrelevant notes', () => { const docs = message().knowledge; expect(retrieve('browser search', docs)).toHaveLength(1); expect(retrieve('gardening', docs)).toHaveLength(0); });
  it('evicts the least recently used exact prompt', () => { const cache = new PromptCache(2); cache.set('a', 'A'); cache.set('b', 'B'); expect(cache.get('a')).toBe('A'); cache.set('c', 'C'); expect(cache.get('b')).toBeUndefined(); cache.clear(); expect(cache.get('a')).toBeUndefined(); });
});

describe('streaming provider client', () => {
  it.each(['https://user:secret@api.example.com/v1', 'https://api.example.com/v1?key=secret', 'file:///tmp/test'])('rejects invalid base URL %s', endpoint => { expect(() => validateEndpoint(endpoint)).toThrow(); });
  it('accepts bridge URLs for server-side validation', () => { expect(validateEndpoint('http://localhost:11434/v1/')).toBe('http://localhost:11434/v1'); });
  it('streams text deltas through the unified proxy', async () => {
    const events = 'data: {"choices":[{"delta":{"content":"Hello "}}]}\n\ndata: {"choices":[{"delta":{"content":"world"},"finish_reason":"stop"}],"usage":{"total_tokens":7}}\n\ndata: [DONE]\n\n';
    const mock = vi.fn().mockResolvedValue(new Response(events, { headers: { 'Content-Type': 'text/event-stream' } })); vi.stubGlobal('fetch',mock);
    try { const deltas: string[] = []; const result = await complete(message().connection,'system','goal',new AbortController().signal,text=>deltas.push(text)); expect(result).toEqual({text:'Hello world',tokens:7}); expect(deltas).toEqual(['Hello ','Hello world']); const [url, init] = mock.mock.calls[0]; expect(url).toBe('/api/chat'); expect(init.redirect).toBe('error'); expect(JSON.parse(init.body).provider).toBe('custom'); expect(JSON.parse(init.body).messages).toHaveLength(2); } finally { vi.unstubAllGlobals(); }
  });
  it('normalizes native Cohere streaming events', async () => { const events = 'event: content-delta\ndata: {"type":"content-delta","delta":{"message":{"content":{"text":"Cohere text"}}}}\n\nevent: message-end\ndata: {"type":"message-end","delta":{"usage":{"tokens":{"input_tokens":4,"output_tokens":3}}}}\n\n'; vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(events,{headers:{'Content-Type':'text/event-stream'}}))); try { expect(await complete({...message().connection,provider:'cohere'},'s','p',new AbortController().signal)).toEqual({text:'Cohere text',tokens:7}); } finally { vi.unstubAllGlobals(); } });
  it.each([401,429])('handles HTTP %s without crashing',async status=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('{}',{status})));try{await expect(complete(message().connection,'s','p',new AbortController().signal)).rejects.toBeInstanceOf(ProviderError);}finally{vi.unstubAllGlobals();}});
  it('rejects truncated streams',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('data: {"choices":[{"delta":{"content":"partial"}}]}\n\n',{headers:{'Content-Type':'text/event-stream'}})));try{await expect(complete(message().connection,'s','p',new AbortController().signal)).rejects.toThrow('ended before completion');}finally{vi.unstubAllGlobals();}});
  it('loads models through the same-origin proxy', async () => { const mock=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:[{id:'test-model'},{id:2}]}))); vi.stubGlobal('fetch',mock); try { expect(await listModels(message().connection,new AbortController().signal)).toEqual(['test-model']);expect(mock.mock.calls[0][0]).toBe('/api/models'); } finally { vi.unstubAllGlobals(); } });
});

describe('worker orchestration', () => {
  it('runs real dependency order with two parallel specialists', async () => { let active = 0; let peak = 0; const prompts: string[] = []; const snapshots: Run[] = []; const call = vi.fn(async (_c, _s, prompt) => { active++; peak = Math.max(peak, active); prompts.push(prompt); await new Promise(r => setTimeout(r, 5)); active--; return { text: `output-${prompts.length}`, tokens: 10 }; }); const run = await executeRun(message(), new AbortController().signal, r => snapshots.push(r), call); expect(run.status).toBe('completed'); expect(run.steps.every(s => s.status === 'completed')).toBe(true); expect(peak).toBe(2); expect(run.calls).toBe(5); expect(run.tokens).toBe(50); expect(run.contextTitles).toEqual(['Browser knowledge']); expect(prompts[3]).toContain('Analyze requirements:'); expect(prompts[3]).toContain('Design the solution:'); expect(exportRun(run)).not.toContain('never-export-this-token'); expect(JSON.stringify(snapshots)).not.toContain('never-export-this-token'); });
  it('does not retry non-retryable failures', async () => { const call = vi.fn(async () => { throw new ProviderError('Authorization failed'); }); const run = await executeRun(message(), new AbortController().signal, () => {}, call); expect(run.status).toBe('failed'); expect(call).toHaveBeenCalledTimes(1); expect(run.steps[0].status).toBe('failed'); expect(run.steps.slice(1).every(s => s.status === 'cancelled')).toBe(true); });
  it('retries transient failures within the two-attempt limit', async () => { let count = 0; const call = vi.fn(async () => { if (++count === 1) throw new ProviderError('Temporary outage', true); return { text: 'ok', tokens: 1 }; }); const run = await executeRun(message(), new AbortController().signal, () => {}, call); expect(run.status).toBe('completed'); expect(run.calls).toBe(6); expect(run.steps[0].attempts).toBe(1); });
  it('stops after bounded transient retries', async () => { const call = vi.fn(async () => { throw new ProviderError('Temporary outage', true); }); const run = await executeRun(message(), new AbortController().signal, () => {}, call); expect(run.status).toBe('failed'); expect(call).toHaveBeenCalledTimes(2); });
  it('cancels active and downstream work', async () => { const controller = new AbortController(); const call = vi.fn(async () => { controller.abort(new DOMException('Stopped', 'AbortError')); throw controller.signal.reason; }); const run = await executeRun(message(), controller.signal, () => {}, call); expect(run.status).toBe('cancelled'); expect(run.steps.every(s => s.status === 'cancelled')).toBe(true); expect(call).toHaveBeenCalledTimes(1); });
  it('labels scripted preview and makes no provider calls', async () => { const input = message(); input.connection.mode = 'demo'; const call = vi.fn(); const run = await executeRun(input, new AbortController().signal, () => {}, call); expect(run.status).toBe('completed'); expect(run.calls).toBe(0); expect(run.tokens).toBe(0); expect(call).not.toHaveBeenCalled(); expect(run.steps.every(s => s.output?.includes('SCRIPTED PREVIEW'))).toBe(true); });
});
