import { useEffect, useRef, useState } from 'react';
import { X, Settings2, Search, LoaderCircle, Trash2 } from 'lucide-react';
import type { Connection } from './lib/types';
import { providers, switchProvider, persistConnection, forgetKeys } from './lib/providers';
import type { Provider } from './lib/providers';
import { listModels } from './lib/provider';
export default function ProviderControls({ connection, setConnection, busy, notify }: { connection: Connection; setConnection: (c: Connection) => void; busy: boolean; notify: (s: string) => void }) {
  const [open, setOpen] = useState(false); const [models, setModels] = useState<string[]>([]); const [loading, setLoading] = useState(false); const [bridge, setBridge] = useState<string | null>(null);
  const drawer = useRef<HTMLElement>(null);
  const provider = connection.provider || 'custom';
  useEffect(() => { const controller = new AbortController(); fetch('/api/providers', { signal: controller.signal }).then(r => r.ok ? r.json() : null).then(data => setBridge(typeof data?.ollamaBridge === 'string' ? data.ollamaBridge : null)).catch(() => {}); return () => controller.abort(); }, []);
  useEffect(() => { if (!open) return; const listener = (e: KeyboardEvent) => { if (e.key === 'Escape') setOpen(false); if (e.key === 'Tab') { const elements = drawer.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled), summary'); if (elements?.length) { const first = elements[0], last = elements[elements.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } } } }; document.addEventListener('keydown', listener); return () => document.removeEventListener('keydown', listener); }, [open]);
  // Fetch OpenRouter's live catalog when selected; fallback presets remain usable on error.
  useEffect(() => { setModels(providers[provider].models); if (provider !== 'openrouter' || connection.mode !== 'remote') return; const controller = new AbortController(); const timer = setTimeout(() => { listModels(connection, controller.signal).then(setModels).catch(e => { if (!controller.signal.aborted) notify(e.message); }); }, 500); return () => { clearTimeout(timer); controller.abort(); }; }, [provider, connection.token, connection.mode]);
  function choose(value: string) {
    if (value === 'demo') { setConnection({ ...connection, mode: 'demo' }); return; }
    if (value === 'ollama') { const c = switchProvider(connection, 'custom'); setConnection({ ...c, endpoint: bridge || 'http://localhost:11434/v1', model: 'llama3.1:8b', token: '' }); setOpen(true); if (!bridge) notify('Ollama requires an administrator-configured bridge. A hosted server cannot access your computer’s localhost.'); return; }
    setConnection(switchProvider(connection, value as Provider));
  }
  async function discover() { setLoading(true); try { const result = await listModels(connection, new AbortController().signal); setModels(result); notify(`Loaded ${result.length} models. You can also enter an ID manually.`); } catch (e) { notify(e instanceof Error ? e.message : 'Model discovery failed.'); } finally { setLoading(false); } }
  function save() { try { persistConnection(connection); notify(connection.saveKey ? 'Provider saved. The API key is stored unencrypted in this browser. Keep this origin and device trusted.' : 'Provider saved. API key stays in memory; any previously saved key for this provider was removed.'); setOpen(false); } catch { notify('Browser storage is unavailable. Connection remains active for this session.'); } }
  return <><div className="provider-compact"><select aria-label="Active provider" disabled={busy} value={connection.mode === 'demo' ? 'demo' : provider} onChange={e => choose(e.target.value)}><option value="demo">Scripted demo</option>{Object.entries(providers).map(([id,p]) => <option value={id} key={id}>{p.name}</option>)}<option value="ollama">💻 Local / Ollama bridge</option></select><button className="icon-button" aria-label="Provider settings" onClick={() => setOpen(true)}><Settings2 size={17}/></button></div>
  <div className="model-statusbar"><span><span className="live-dot"/>{connection.mode === 'demo' ? 'Scripted preview · no model' : connection.model || 'Select a model'}</span><span>{connection.mode === 'demo' ? 'Demo' : providers[provider].tier} · {busy ? 'Streaming workflow' : 'Ready'}</span></div>
  {open && <div className="provider-overlay" onClick={e => { if (e.target === e.currentTarget) setOpen(false); }}><section ref={drawer} className="provider-drawer panel" role="dialog" aria-modal="true" aria-labelledby="provider-title"><div className="section-heading"><h2 id="provider-title">Provider & model</h2><button className="icon-button" aria-label="Close provider settings" onClick={() => setOpen(false)} autoFocus><X size={20}/></button></div><p className="help-text">Your browser sends requests through this deployment's /api/chat proxy. Bring your own key; public visitors cannot use server credits.</p><label>Provider<select disabled={busy} value={connection.mode === 'demo' ? 'demo' : provider} onChange={e => choose(e.target.value)}><option value="demo">Scripted demo</option>{Object.entries(providers).map(([id,p]) => <option value={id} key={id}>{p.name}</option>)}<option value="ollama">💻 Local / Ollama bridge</option></select></label>
  {provider === 'custom' && <><label>Custom API base URL<input disabled={busy} value={connection.endpoint} placeholder="https://your-api.example/v1" onChange={e => setConnection({ ...connection, endpoint: e.target.value })}/></label><p className="help-text">Hosted origins must be approved by the server administrator. Ollama defaults to localhost:11434/v1 only when the server runs beside Ollama. For a cloud deployment, configure a secure bridge URL.</p><button className="button secondary" disabled={busy} onClick={() => choose('ollama')}>Use Ollama preset</button></>}
  <label>API key<input disabled={busy} type="password" autoComplete="off" spellCheck={false} value={connection.token} onChange={e => setConnection({ ...connection, token: e.target.value })} placeholder="Your provider key"/></label><label className="checkbox-label"><input type="checkbox" disabled={busy} checked={Boolean(connection.saveKey)} onChange={e => setConnection({ ...connection, saveKey: e.target.checked })}/>Remember key on this browser</label><p className="key-warning">Optional localStorage storage is not encrypted. Scripts running on this origin can read saved keys. Use restricted keys on trusted devices only. Keys are never included in workspace exports.</p>
  <div className="form-row"><label>Model ID<input disabled={busy} list="provider-catalog" value={connection.model} onChange={e => setConnection({ ...connection, model: e.target.value })} placeholder="Type any supported model ID"/><datalist id="provider-catalog">{models.map(id => <option value={id} key={id}/>)}</datalist></label><button className="button secondary" disabled={busy || loading || connection.mode === 'demo'} onClick={() => void discover()}>{loading ? <LoaderCircle size={15} className="spin"/> : <Search size={15}/>}Load</button></div><div className="model-presets">{providers[provider].models.map(id => <button key={id} disabled={busy} onClick={() => setConnection({ ...connection, model: id })}>{id}</button>)}</div><p className="help-text">Model availability depends on your provider account. Groq's optional groq/ prefix is stripped; OpenRouter slugs are preserved.</p><label>Output limit<select disabled={busy} value={connection.maxTokens} onChange={e => setConnection({ ...connection, maxTokens: Number(e.target.value) })}>{[512,1024,2048,4096].map(n => <option value={n} key={n}>{n.toLocaleString()} tokens</option>)}</select></label><details><summary>Authorized server credits</summary><p className="help-text">Only for users given a deployment access token by the administrator. This token is never persisted. Leave empty to use your own API key.</p><label>Deployment access token<input disabled={busy} type="password" autoComplete="off" value={connection.serverAccessToken || ''} onChange={e => setConnection({ ...connection, serverAccessToken: e.target.value })}/></label></details><button className="button primary" disabled={busy} onClick={save}>Save provider</button><button className="button secondary forget-button" disabled={busy} onClick={() => { try { forgetKeys(); setConnection({ ...connection, token: '', saveKey: false, serverAccessToken: '' }); notify('All saved provider keys removed from this browser.'); } catch { notify('Could not clear browser storage. Clear this site’s data in browser settings.'); } }}><Trash2 size={14}/>Forget all saved keys</button></section></div>}</>;
}
